
---
version: "2"
volumes:
    grav-data:
      driver: local
      driver_opts:
        type: none
        device: $PWD/grav
        o: bind
  
services:
    docker-grav:
        image: grav-xdebug:latest
        container_name: grav-xdebug
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ./grav-data:/var/www/html:rw
            - ./logs/xdebug:/logs/xdebug
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        
