volumes:
    grav-data:
      driver: local
      driver_opts:
        type: none
        device: $PWD/grav
        o: bind
  
services:
    grav-xdebug:
        build: ./
        ports:
            - "8080:80"
        volumes:
            - ./grav-data/grav:/var/www/html/grav:rw
            - ./logs/xdebug:/logs/xdebug
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        
